os:
  - linux
language: node_js
node_js:
  - '10'
dist: xenial
sudo: required
services:
  - xvfb
addons:
  chrome: stable
before_script:
  - export DISPLAY=:99.0
install:
  - npm set progress=false
  - npm install
  - sudo snap install snapcraft --classic
script:
  - npm run electron:linux
deploy:
  - provider: releases
    api_key: $GITHUB_KEY
    file_glob: true
    file:
      - "release/App Outlet-*.AppImage"
      - "release/app-outlet_*_amd64.deb"
      - "release/app-outlet_*_amd64.snap"
    skip_cleanup: true
    on:
      tags: true

  - provider: snap
    snap: release/app-outlet_*_amd64.snap
    channel: edge
    skip_cleanup: true
