os:
  - linux
language: node_js
node_js:
  - '10'
dist: xenial
sudo: required
services:
  - xvfb
addons:
  chrome: stable
before_script:
  - export DISPLAY=:99.0
install:
  - npm set progress=false
  - npm install
script:
  - npm run electron:linux
deploy:
  provider: releases
  api_key: $GITHUB_KEY
  file_glob: true
  file:
    - "release/App Outlet-*.AppImage"
    - "release/app-outlet_*.snap"
  skip_cleanup: true
  on:
    tags: true
