os:
  - linux
language: node_js
node_js:
  - "10"
dist: xenial
sudo: required
services:
  - xvfb
addons:
  chrome: stable
before_script:
  - export DISPLAY=:99.0
install:
  - npm set progress=false
  - npm install
script:
  - npm run electron:linux
  - bash export-version.sh
  - tar -zcvf release/app-outlet_${PACKAGE_VERSION}_amd64.tar.gz release/linux-unpacked
deploy:
  - provider: releases
    api_key: $GITHUB_KEY
    file_glob: true
    file:
      - "release/App Outlet-*.AppImage"
      - "release/app-outlet_*_amd64.deb"
      - "release/app-outlet_*_amd64.tar.gz"
    skip_cleanup: true
    on:
      branch: master
      tags: true

  - provider: snap
    snap: "release/*.snap"
    channel: stable
    skip_cleanup: true
    on:
      branch: master
      tags: true
