name: app-outlet
version: '1.0.5'
summary: An univeral linux app store. Find Snaps, Flatpaks and AppImages
description: |
  App Outlet is the better and easier way to find your linux apps on the web. Here you can find more than 3000 apps!

grade: stable
confinement: strict
icon: src/assets/icon.png

architectures:
  - build-on: amd64
    run-on: amd64
parts:
  app-outlet:
    plugin: nodejs
    source: https://github.com/app-outlet/app-outlet.git
    build-packages: [nodejs]
    override-build: npm run electron:linux
