name: app-outlet
title: App Outlet
version: '1.0.4'
summary: An univeral linux app store. Find Snaps, Flatpaks and AppImages
description: |
  App Outlet is the better and easier way to find your linux apps on the web. Here you can find more than 3000 apps!

grade: stable
confinement: strict
icon: src/assets/icon.png
license: MIT
architectures:
  - build-on: amd64
    run-on: amd64
parts:
  my-part:
    plugin: nil
